### ISSUE TITLE
Error occurs when using /nick with an emoji in the new nickname

### ISSUE THREAD

**Issue by Joshua-Burt** [Joshua-Burt/BlockBot#24]
```
Ignoring exception in command nick:
Traceback (most recent call last):
  File "...\Python311\Lib\site-packages\discord\commands\core.py", line 124, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\discord\commands\core.py", line 982, in _invoke
    await self.callback(ctx, **kwargs)
  File "...\BlockObama 2.0\main.py", line 264, in nick
    await ctx.respond(f"Changed {user.name}'s nickname to {new_nick}", ephemeral=True)
  File "...\Python311\Lib\site-packages\discord\commands\context.py", line 282, in respond
    return await self.interaction.response.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\discord\interactions.py", line 825, in send_message
    await self._locked_response(
  File "...\Python311\Lib\site-packages\discord\interactions.py", line 1090, in _locked_response
    await coro
  File "...\Python311\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\Python311\Lib\site-packages\discord\bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "...\Python311\Lib\site-packages\discord\commands\core.py", line 375, in invoke
    await injected(ctx)
  File "...\Python311\Lib\site-packages\discord\commands\core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: HTTPException: 400 Bad Request (error code: 40060): Interaction has already been acknowledged.
```

**Comment by Joshua-Burt** [comment]
Cannot replicate. Likely unrelated to /nick command
