### ISSUE TITLE
Error when new user joins a server

### ISSUE THREAD

**Issue by Joshua-Burt** [Joshua-Burt/BlockBot#29]
```
Traceback (most recent call last):
  File "...\Python311\Lib\site-packages\discord\client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "...\main.py", line 72, in on_member_join
    json_utils.add_user(member.id)
  File "...\json_utils.py", line 47, in add_user
    users_file.append({
    ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'append'
```

**Comment by Joshua-Burt** [comment]
Fixed in 9abc948
